# Theme config: https://mmistakes.github.io/minimal-mistakes/docs/configuration/
plugins:
  - jekyll-include-cache

# GLOBAL THEME CONFIG
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
minimal_mistakes_skin: "neon" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

title: "Entregas Visual"
title_separator: "|"
subtitle: "Computación Visual 2020-2"

url: "https://visual-2020-2.github.io"
repository: "visual-2020-2/visual-2020-2.github.io"

breadcrumbs: true

include: ["_pages"]

collections:
  sketches:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _sketches
  - scope:
      path: ""
      type: sketches
    values:
      layout: single
      author_profile: false
      share: true

# Necessary to load p5.js library (in all output files)
head_scripts:
  - https://cdn.jsdelivr.net/npm/p5@1.1.9/lib/p5.js
