# Theme config: https://mmistakes.github.io/minimal-mistakes/docs/configuration/
plugins:
  - jekyll-include-cache

# GLOBAL THEME CONFIG
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
minimal_mistakes_skin: "air" # "default"
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

title: "Entregas Visual"
title_separator: "|"
subtitle: "Computación Visual 2020-2"

url: "https://visual-2020-2.github.io"
repository: "visual-2020-2/visual-2020-2.github.io"

breadcrumbs: true

include: ["_pages"]

collections:
  sketches:
    output: true
    #permalink: /:collection/:name/
  imaging:
    output: true
  illusions:
    output: true
    #permalink: /:collection/:name/
  light:
    output: true
    #permalink: /:collection/:name/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _sketches
  - scope:
      path: ""
      type: sketches
    values:
      layout: single
      author_profile: false
      share: false
  # _imaging
  - scope:
      path: ""
      type: imaging
    values:
      layout: single
      author_profile: false
      share: false
  # _illusions
  - scope:
      path: ""
      type: illusions
    values:
      layout: single
      author_profile: false
      share: false
  # _light
  - scope:
      path: ""
      type: light
    values:
      layout: single
      author_profile: false
      share: false
  # _project
  - scope:
      path: ""
      type: project
    values:
      layout: single
      author_profile: false
      share: false

# Necessary to load p5.js library (in all output files)
head_scripts:
  - https://cdn.jsdelivr.net/npm/p5@1.1.9/lib/p5.js
  - https://cdn.jsdelivr.net/npm/ml5@0.5.0/dist/ml5.min.js
